# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ecf813ed508827d4b8c3b3ff906c712258d51a9210db659e6a3e1e40c8f0db4179dfffef232e2fc93c3daa24ff8402e949a6c9830b41ca9c197dc35aab4c8e2

test:
  secret_key_base: a3a5e4a16d63c77dcb7e03a44422686fdb26874cea9fe060a1ce11d6e99f144c141a88c4da328c4495977cad36990332d6a7f8cbd3a54e432eac0bc212041313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
